# Generated by Django 4.0.8 on 2026-02-02 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventaris', '0002_maintenancephoto'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenanceschedule',
            name='trigger_type',
            field=models.CharField(choices=[('TIME', 'Time-based'), ('USAGE', 'Usage-based'), ('CONDITION', 'Condition-based'), ('EVENT', 'Event-based')], default='TIME', max_length=20),
        ),
        migrations.AlterField(
            model_name='maintenanceschedule',
            name='next_due_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='maintenanceschedule',
            name='period',
            field=models.CharField(blank=True, choices=[('HARIAN', 'Harian'), ('MINGGUAN', 'Mingguan'), ('BULANAN', 'Bulanan'), ('TAHUNAN', 'Tahunan')], max_length=20, null=True),
        ),
    ]
