# Generated by Django 4.0.8 on 2026-02-02 03:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inventaris', '0003_maintenanceschedule_trigger_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetMeterReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reading_type', models.CharField(choices=[('KM', 'Kilometer'), ('HOUR', 'Jam Operasi'), ('CYCLE', 'Cycle Count')], max_length=20)),
                ('reading_value', models.PositiveIntegerField()),
                ('reading_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('note', models.TextField(blank=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meter_readings', to='inventaris.asset')),
                ('recorded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-reading_at', '-id'],
            },
        ),
    ]
