# Generated by Django 4.0.8 on 2026-02-02 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventaris', '0004_assetmeterreading'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenanceschedule',
            name='last_usage_value',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='maintenanceschedule',
            name='next_due_usage',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='maintenanceschedule',
            name='usage_interval',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
