# Generated by Django 4.0.8 on 2026-02-02 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventaris', '0005_maintenanceschedule_last_usage_value_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenanceschedule',
            name='plan_name',
            field=models.CharField(default='Rencana Pemeliharaan', max_length=150),
        ),
    ]
