# Generated by Django 4.0.8 on 2026-02-02 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventaris', '0006_maintenanceschedule_plan_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenanceschedule',
            name='usage_reading_type',
            field=models.CharField(blank=True, choices=[('KM', 'Kilometer'), ('HOUR', 'Jam Operasi'), ('CYCLE', 'Cycle Count')], max_length=20, null=True),
        ),
    ]
